import '../core/models/memory_game_info/memory_game_info.dart';

List<MemoryGameInfo> memoryGameInfos = [
  MemoryGameInfo(
    urls: [
      "images/1.jpg",
      "images/2.jpg",
    ],
    level: 1,
    horizontalCount: 2,
    verticalCount: 2,
  ),
  MemoryGameInfo(
    urls: [
      "images/1.jpg",
      "images/2.jpg",
      "images/3.jpg",
    ],
    level: 2,
    horizontalCount: 2,
    verticalCount: 3,
  ),
  MemoryGameInfo(
    urls: [
      "images/1.jpg",
      "images/2.jpg",
      "images/3.jpg",
      "images/4.jpg",
    ],
    level: 3,
    horizontalCount: 2,
    verticalCount: 4,
  ),
  MemoryGameInfo(
    urls: [
      "images/1.jpg",
      "images/2.jpg",
      "images/3.jpg",
      "images/4.jpg",
      "images/5.jpg",
    ],
    level: 4,
    horizontalCount: 2,
    verticalCount: 5,
  ),
  MemoryGameInfo(
    urls: [
      "images/1.jpg",
      "images/2.jpg",
      "images/3.jpg",
      "images/4.jpg",
      "images/5.jpg",
      "images/6.jpg",
    ],
    level: 5,
    horizontalCount: 3,
    verticalCount: 4,
  ),
  MemoryGameInfo(
    urls: [
      "images/1.jpg",
      "images/2.jpg",
      "images/3.jpg",
      "images/4.jpg",
      "images/5.jpg",
      "images/6.jpg",
      "images/7.jpg",
      "images/8.jpg",
    ],
    level: 6,
    horizontalCount: 4,
    verticalCount: 4,
  ),
  MemoryGameInfo(
    urls: [
      "images/1.jpg",
      "images/2.jpg",
      "images/3.jpg",
      "images/4.jpg",
      "images/5.jpg",
      "images/6.jpg",
      "images/7.jpg",
      "images/8.jpg",
      "images/9.jpg",
    ],
    level: 7,
    horizontalCount: 3,
    verticalCount: 6,
  ),
  MemoryGameInfo(
    urls: [
      "images/1.jpg",
      "images/2.jpg",
      "images/3.jpg",
      "images/4.jpg",
      "images/5.jpg",
      "images/6.jpg",
      "images/7.jpg",
      "images/8.jpg",
      "images/9.jpg",
      "images/10.jpg",
    ],
    level: 8,
    horizontalCount: 4,
    verticalCount: 5,
  ),
  MemoryGameInfo(
    urls: [
      "images/1.jpg",
      "images/2.jpg",
      "images/3.jpg",
      "images/4.jpg",
      "images/5.jpg",
      "images/6.jpg",
      "images/7.jpg",
      "images/8.jpg",
      "images/9.jpg",
      "images/10.jpg",
      "images/11.jpg",
      "images/12.jpg",
    ],
    level: 9,
    horizontalCount: 4,
    verticalCount: 6,
  ),
  MemoryGameInfo(
    urls: [
      "images/1.jpg",
      "images/2.jpg",
      "images/3.jpg",
      "images/4.jpg",
      "images/5.jpg",
      "images/6.jpg",
      "images/7.jpg",
      "images/8.jpg",
      "images/9.jpg",
      "images/10.jpg",
      "images/11.jpg",
      "images/12.jpg",
      "images/13.jpg",
      "images/14.jpg",
    ],
    level: 10,
    horizontalCount: 4,
    verticalCount: 7,
  ),
  MemoryGameInfo(
    urls: [
      "images/1.jpg",
      "images/2.jpg",
      "images/3.jpg",
      "images/4.jpg",
      "images/5.jpg",
      "images/6.jpg",
      "images/7.jpg",
      "images/8.jpg",
      "images/9.jpg",
      "images/10.jpg",
      "images/11.jpg",
      "images/12.jpg",
      "images/13.jpg",
      "images/14.jpg",
      "images/15.jpg",
    ],
    level: 11,
    horizontalCount: 5,
    verticalCount: 6,
  ),
  MemoryGameInfo(
    urls: [
      "images/1.jpg",
      "images/2.jpg",
      "images/3.jpg",
      "images/4.jpg",
      "images/5.jpg",
      "images/6.jpg",
      "images/7.jpg",
      "images/8.jpg",
      "images/9.jpg",
      "images/10.jpg",
      "images/11.jpg",
      "images/12.jpg",
      "images/13.jpg",
      "images/14.jpg",
      "images/15.jpg",
      "images/16.jpg",
    ],
    level: 12,
    horizontalCount: 4,
    verticalCount: 8,
  ),
  MemoryGameInfo(
    urls: [
      "images/1.jpg",
      "images/2.jpg",
      "images/3.jpg",
      "images/4.jpg",
      "images/5.jpg",
      "images/6.jpg",
      "images/7.jpg",
      "images/8.jpg",
      "images/9.jpg",
      "images/10.jpg",
      "images/11.jpg",
      "images/12.jpg",
      "images/13.jpg",
      "images/14.jpg",
      "images/15.jpg",
      "images/16.jpg",
      "images/17.jpg",
      "images/18.jpg",
    ],
    level: 13,
    horizontalCount: 6,
    verticalCount: 6,
  ),
  MemoryGameInfo(
    urls: [
      "images/1.jpg",
      "images/2.jpg",
      "images/3.jpg",
      "images/4.jpg",
      "images/5.jpg",
      "images/6.jpg",
      "images/7.jpg",
      "images/8.jpg",
      "images/9.jpg",
      "images/10.jpg",
      "images/11.jpg",
      "images/12.jpg",
      "images/13.jpg",
      "images/14.jpg",
      "images/15.jpg",
      "images/16.jpg",
      "images/17.jpg",
      "images/18.jpg",
    ],
    level: 14,
    horizontalCount: 6,
    verticalCount: 6,
  ),
  MemoryGameInfo(
    urls: [
      "images/1.jpg",
      "images/2.jpg",
      "images/3.jpg",
      "images/4.jpg",
      "images/5.jpg",
      "images/6.jpg",
      "images/7.jpg",
      "images/8.jpg",
      "images/9.jpg",
      "images/10.jpg",
      "images/11.jpg",
      "images/12.jpg",
      "images/13.jpg",
      "images/14.jpg",
      "images/15.jpg",
      "images/16.jpg",
      "images/17.jpg",
      "images/18.jpg",
      "images/19.jpg",
      "images/20.jpg",
    ],
    level: 15,
    horizontalCount: 5,
    verticalCount: 8,
  ),
  MemoryGameInfo(
    urls: [
      "images/1.jpg",
      "images/2.jpg",
      "images/3.jpg",
      "images/4.jpg",
      "images/5.jpg",
      "images/6.jpg",
      "images/7.jpg",
      "images/8.jpg",
      "images/9.jpg",
      "images/10.jpg",
      "images/11.jpg",
      "images/12.jpg",
      "images/13.jpg",
      "images/14.jpg",
      "images/15.jpg",
      "images/16.jpg",
      "images/17.jpg",
      "images/18.jpg",
      "images/19.jpg",
      "images/20.jpg",
      "images/21.jpg",
    ],
    level: 16,
    horizontalCount: 6,
    verticalCount: 7,
  ),
  MemoryGameInfo(
    urls: [
      "images/1.jpg",
      "images/2.jpg",
      "images/3.jpg",
      "images/4.jpg",
      "images/5.jpg",
      "images/6.jpg",
      "images/7.jpg",
      "images/8.jpg",
      "images/9.jpg",
      "images/10.jpg",
      "images/11.jpg",
      "images/12.jpg",
      "images/13.jpg",
      "images/14.jpg",
      "images/15.jpg",
      "images/16.jpg",
      "images/17.jpg",
      "images/18.jpg",
      "images/19.jpg",
      "images/20.jpg",
      "images/21.jpg",
    ],
    level: 17,
    horizontalCount: 6,
    verticalCount: 7,
  ),
  MemoryGameInfo(
    urls: [
      "images/1.jpg",
      "images/2.jpg",
      "images/3.jpg",
      "images/4.jpg",
      "images/5.jpg",
      "images/6.jpg",
      "images/7.jpg",
      "images/8.jpg",
      "images/9.jpg",
      "images/10.jpg",
      "images/11.jpg",
      "images/12.jpg",
      "images/13.jpg",
      "images/14.jpg",
      "images/15.jpg",
      "images/16.jpg",
      "images/17.jpg",
      "images/18.jpg",
      "images/19.jpg",
      "images/20.jpg",
      "images/21.jpg",
    ],
    level: 18,
    horizontalCount: 6,
    verticalCount: 7,
  ),
  MemoryGameInfo(
    urls: [
      "images/1.jpg",
      "images/2.jpg",
      "images/3.jpg",
      "images/4.jpg",
      "images/5.jpg",
      "images/6.jpg",
      "images/7.jpg",
      "images/8.jpg",
      "images/9.jpg",
      "images/10.jpg",
      "images/11.jpg",
      "images/12.jpg",
      "images/13.jpg",
      "images/14.jpg",
      "images/15.jpg",
      "images/16.jpg",
      "images/17.jpg",
      "images/18.jpg",
      "images/19.jpg",
      "images/20.jpg",
      "images/21.jpg",
    ],
    level: 19,
    horizontalCount: 6,
    verticalCount: 7,
  ),
  MemoryGameInfo(
    urls: [
      "images/1.jpg",
      "images/2.jpg",
      "images/3.jpg",
      "images/4.jpg",
      "images/5.jpg",
      "images/6.jpg",
      "images/7.jpg",
      "images/8.jpg",
      "images/9.jpg",
      "images/10.jpg",
      "images/11.jpg",
      "images/12.jpg",
      "images/13.jpg",
      "images/14.jpg",
      "images/15.jpg",
      "images/16.jpg",
      "images/17.jpg",
      "images/18.jpg",
      "images/19.jpg",
      "images/20.jpg",
      "images/21.jpg",
    ],
    level: 20,
    horizontalCount: 6,
    verticalCount: 7,
  ),
  MemoryGameInfo(
    urls: [
      "images/1.jpg",
      "images/2.jpg",
      "images/3.jpg",
      "images/4.jpg",
      "images/5.jpg",
      "images/6.jpg",
      "images/7.jpg",
      "images/8.jpg",
      "images/9.jpg",
      "images/10.jpg",
      "images/11.jpg",
      "images/12.jpg",
      "images/13.jpg",
      "images/14.jpg",
      "images/15.jpg",
      "images/16.jpg",
      "images/17.jpg",
      "images/18.jpg",
      "images/19.jpg",
      "images/20.jpg",
      "images/21.jpg",
    ],
    level: 21,
    horizontalCount: 6,
    verticalCount: 7,
  ),
];
